# Schemas for collective_agreements (migrés depuis schemas/collective_agreement.py).
from .requests import (
    AssignAgreementBody,
    CollectiveAgreementCatalogCreate,
    CollectiveAgreementCatalogUpdate,
    CompanyCollectiveAgreementCreate,
    ExtractRulesBatchRequest,
    GetUploadUrlBody,
    KaliImportBatchRequest,
    KaliImportRequest,
    QuestionRequest,
)
from .responses import (
    CollectiveAgreementCatalog,
    CollectiveAgreementCatalogBase,
    CompanyCollectiveAgreement,
    CompanyCollectiveAgreementWithDetails,
    ExtractRulesBatchResponse,
    ExtractRulesResponse,
    KaliImportBatchResponse,
    KaliImportResponse,
    QuestionResponse,
    RollbackRulesResponse,
    RulesStatusResponse,
    UploadUrlResponse,
)

__all__ = [
    "AssignAgreementBody",
    "CollectiveAgreementCatalog",
    "CollectiveAgreementCatalogBase",
    "CollectiveAgreementCatalogCreate",
    "CollectiveAgreementCatalogUpdate",
    "CompanyCollectiveAgreement",
    "CompanyCollectiveAgreementCreate",
    "CompanyCollectiveAgreementWithDetails",
    "ExtractRulesBatchRequest",
    "ExtractRulesBatchResponse",
    "ExtractRulesResponse",
    "GetUploadUrlBody",
    "KaliImportBatchRequest",
    "KaliImportBatchResponse",
    "KaliImportRequest",
    "KaliImportResponse",
    "QuestionRequest",
    "QuestionResponse",
    "RollbackRulesResponse",
    "RulesStatusResponse",
    "UploadUrlResponse",
]
