"""Nomenclature officielle du « Code de cotisation » DSN (S21.G00.81.001).

Extraite du cahier technique NEODeS CT2026.1.2 (2025-12-24), publié par
net-entreprises :
https://www.net-entreprises.fr/media/documentation/dsn-cahier-technique-2026.1.pdf

Donnée publique, pas un paramétrage client. Elle sert à nommer les codes lus
dans les DSN du cabinet et à contrôler ceux que notre export émet.
"""

from __future__ import annotations

from typing import Dict, Optional

CODE_COTISATION_LIBELLE: Dict[str, str] = {
    "001": "Exonération de cotisations au titre de l'emploi d'un apprenti (loi de 1979)",
    "002": "Exonération de cotisations au titre de l'emploi d'un apprenti (loi de 1987)",
    "003": "Exonération de cotisations au titre de l'emploi d'un apprenti (loi de 1992)",
    "004": "Exonération de cotisations au titre de l'emploi d'un salarié en contrat d'accès à l'emploi",
    "005": "Cotisation Développement du paritarisme",
    "006": "Exonération de cotisations au titre de l'emploi d'un salarié en contrat d'accompagnement dans l'emploi",
    "007": "Cotisation FAF (Fonds d'Assurance formation)",
    "008": "Exonération de cotisations au titre de l'emploi d'un salarié en contrat de professionnalisation",
    "009": "Exonération de cotisations applicable aux associations intermédiaires",
    "010": "Exonération de cotisations applicable aux entreprises des bassins d'emploi à redynamiser",
    "011": "Exonération de cotisations applicable au créateur ou repreneur d'entreprise",
    "012": "Exonération de cotisations applicable dans les DOM",
    "013": "Exonération de cotisations applicable aux entreprises et associations d'aide à domicile",
    "014": "Exonérations de cotisations applicable aux entreprises innovantes, universitaires ou de croissance",
    "015": "Exonération de cotisations applicable aux entreprises en zones franches urbaines",
    "016": "Exonération de cotisations applicable aux organismes d'intérêt général en zones de revitalisation rurale",
    "017": "Exonération de cotisations applicable aux structures agréées de l'aide sociale",
    "018": "Réduction générale des cotisations patronales de sécurité sociale et d'assurance chômage",
    "019": "Réduction de cotisations applicable aux entreprises des zones de restructuration de la défense",
    "020": "Réduction de cotisations au titre de l'embauche du 1er au 50ème salarié en zones de revitalisation rurale",
    "021": "Déduction patronale au titre des heures supplémentaires",
    "022": "Exonération de cotisations applicable à une gratification de stage",
    "023": "Activation du bénéfice de l'aide au paiement des cotisations », «",
    "024": "Cotisation assise sur le nombre d'heures d'intérim",
    "025": "Exonération de cotisations au titre de l’emploi d’un salarié en chantier et atelier d'insertion",
    "026": "Contribution aux régimes supplémentaires de retraite à prestations définies - Prime », «",
    "027": "Exonération Personnel technique CUMA, hors ateliers",
    "028": "Réduction Travailleur Occasionnel",
    "029": "Réduction employeurs petit pool IEG",
    "030": "Cotisation employeurs régime spécial maladie IEG Complémentaire",
    "031": "Cotisation salariés régime spécial maladie IEG Complémentaire",
    "032": "Cotisation salariés régime maladie IEG spécial Solidarité",
    "033": "Cotisation employeurs complément d'invalidité IEG",
    "034": "Cotisation employeurs régime de droit commun IEG (population adossée)",
    "035": "Cotisation employeurs régime spécial IEG (population adossée)",
    "036": "Cotisation employeurs régime spécial IEG (population non adossée)",
    "037": "Cotisation salariés régime de droit commun IEG (population adossée)",
    "038": "Cotisation salariés régime spécial IEG (population non adossée)",
    "039": "Cotisations employeurs petit pool IEG",
    "040": "Cotisation AC : assurance chômage sur rémunérations brutes après déduction",
    "041": "Cotisation AC majorée 1 : application d’une majoration AC + 0,5% sur les contrats d’usage inférieurs ou égaux à 3 mois",
    "042": "Cotisation AC majorée 2 : application d’une majoration AC + 3% sur les contrats d’accroissement temporaire d’activité inférieurs ou égaux à 1 mois",
    "043": "Cotisation maladie Alsace-Moselle sur les avantages de retraite », «",
    "044": "Exonération de cotisation chômage pour les moins de 26 ans",
    "045": "Cotisation Accident du travail",
    "046": "Cotisation AEF Bourse de l'emploi",
    "047": "Cotisation AEF CESA",
    "048": "Cotisation AGS : assurance garantie des salaires sur rémunérations brutes après déduction",
    "049": "Cotisation Allocation de logement (FNAL)",
    "050": "CSG au taux de 9.20% + RDS sur revenus de remplacement », «",
    "051": "Cotisation Formation professionnelle ADEFA",
    "053": "Cotisation Formation professionnelle additionnelle FAFSEA",
    "054": "Cotisation Formation professionnelle AREFA",
    "056": "Cotisation Formation professionnelle FAFSEA",
    "057": "Cotisation Formation professionnelle FAFSEA CDD",
    "058": "Cotisation Formation professionnelle FAFSEA des communes forestières",
    "059": "Cotisation individuelle Prévoyance-Assurance-Mutuelle pour la période et l'affiliation concernées",
    "060": "Cotisation IRCANTEC Tranche A",
    "061": "Cotisation IRCANTEC Tranche B",
    "062": "Dépense déductible liée aux travaux d’accessibilité », «",
    "063": "Dépense déductible liée au maintien et à la reconversion professionnelle », «",
    "064": "Dépense déductible liée aux prestations d’accompagnement et de sensibilisation », «",
    "065": "Cotisation CRPCEN",
    "066": "Cotisation caisse de congés spectacles",
    "067": "Contribution OETH nette après écrêtement (pour les millésimes strictement antérieurs à 2025) », «",
    "068": "Contribution solidarité autonomie",
    "069": "Contribution sur avantage de pré-retraite entreprise à dater du 11/10/2007 (CAPE)",
    "070": "Contribution sur avantage de pré-retraite entreprise aux taux normal (CAPE)",
    "071": "Contribution forfait social",
    "072": "Contribution sociale généralisée/salaires partiellement déductibles",
    "073": "CSG/CRDS sur participation intéressement épargne salariale",
    "074": "Cotisation Allocation familiale - taux normal",
    "075": "Cotisation Assurance Maladie",
    "076": "Cotisation Assurance Vieillesse",
    "077": "Montant de la retenue à la source effectuée sur les salaires versés aux personnes domiciliées hors de France",
    "078": "Pénalité de 1% emploi sénior",
    "079": "Remboursement de la dette sociale",
    "080": "Exonération de la contribution supplémentaire à l’apprentissage (CSA) » et «",
    "081": "Versement mobilité",
    "082": "Versement mobilité additionnel",
    "088": "Exonération versement mobilité",
    "089": "Exonération Contrat Initiative Emploi",
    "090": "Exonération accueillants familiaux",
    "091": "Cotisation Service de santé au travail",
    "092": "Cotisation Association pour l'emploi des cadres ingénieurs et techniciens de l'agriculture (APECITA)",
    "093": "Contribution sur indemnités de mise à la retraite ou de rupture conventionnelle individuelle",
    "094": "Exonération cotisations Allocations familiales (SICAE)",
    "096": "Cotisation CRPNPAC au fonds de retraite",
    "097": "Cotisation CRPNPAC au fonds d'assurance",
    "098": "Cotisation CRPNPAC au fonds de majoration",
    "099": "Contribution stock options",
    "100": "Contribution au financement du dialogue social",
    "101": "Association Mutualisation du Coût Inaptitude",
    "102": "Complément de cotisation Allocation Familiale",
    "103": "Contribution actions gratuites",
    "104": "Pénibilité Cotisation de base",
    "105": "Montant de cotisation Régime Unifié Agirc-Arrco, y compris Apec",
    "106": "Réduction générale des cotisations patronales de retraite complémentaire",
    "107": "Forfait marin",
    "108": "Demi-rôle marin",
    "109": "Exonération de cotisations salariales de retraite complémentaire au titre de l'emploi d'un apprenti",
    "110": "Exonération de cotisations patronales de retraite complémentaire applicable dans les DOM (LODEOM) SMIC 130% à 220%",
    "111": "Exonération de cotisations de retraite complémentaire applicable aux entreprises et associations d'aide à domicile",
    "112": "Exonération de cotisations patronales de retraite complémentaire applicable dans les DOM (LODEOM) SMIC 170% à 270%",
    "113": "Exonération de cotisations patronales de retraite complémentaire applicable dans les DOM (LODEOM) SMIC 170% à 350%",
    "114": "Montant de réduction des heures supplémentaires/complémentaires",
    "115": "Cotisation Assurance Maladie pour le Régime Local Alsace Moselle",
    "116": "Cotisation absente de la norme en cas de régularisation prud'homale",
    "128": "Contribution à la formation professionnelle (CFP)",
    "129": "Contribution dédiée au financement du Compte Personnel de Formation pour les titulaires de CDD (CPF-CDD)",
    "130": "Part principale de la taxe d'apprentissage",
    "131": "Cotisation régime unifié Agirc-Arrco",
    "132": "Cotisation Apec",
    "133": "Contribution maladie spécifique Mayotte",
    "140": "Contribution conventionnelle au financement du dialogue social",
    "141": "Contribution conventionnelle à la formation professionnelle",
    "142": "Cotisation régime unifié Agirc-Arrco (part patronale tranche T1)",
    "143": "Contribution au compte professionnel de prévention (C2P)",
    "144": "Cotisation CAVEC - classe C",
    "145": "Cotisation CAVEC - classe D",
    "146": "Cotisation régime unifié Agirc-Arrco (part patronale tranche T2)",
    "300": "[FP] Cotisations normales (part salariale)",
    "301": "[FP] Cotisations normales (part patronale)",
    "302": "[FP] Surcotisation huit trimestres (part salariale)",
    "303": "[FP] Validation de services (part salariale)",
    "304": "[FP] Cotisations Nouvelle Bonification Indiciaire (part salariale)",
    "305": "[FP] Cotisations Nouvelle Bonification Indiciaire (part patronale)",
    "306": "[FP] Cotisations sur indemnité de feu (part salariale)",
    "307": "[FP] Cotisations sur indemnité de feu (part patronale)",
    "308": "[FP] Cotisation sur bonification sapeur pompier (part salariale)",
    "309": "[FP] Cotisation sur prime sur sujetion des aides soignantes (part salariale)",
    "310": "[FP] Cotisation sur prime sur sujetion des aides soignantes (part patronale)",
    "311": "[FP] Cotisation RAFP (part salariale)",
    "312": "[FP] Cotisation RAFP (part patronale)",
    "313": "[FP] Cotisations pour pension sur ISS ou PSS (part salariale)",
    "314": "[FP] Cotisations pour pension sur ISS ou PSS (part patronale)",
    "315": "[FP] Cotisations pour pension sur IR (part salariale)",
    "316": "[FP] Cotisations pour pension sur IR (part patronale)",
    "317": "[FP] Cotisations pour pension sur IMT (part salariale)",
    "318": "[FP] Cotisations pour pension sur IMT (part patronale)",
    "319": "[FP] Cotisations pour l'allocation temporaire d'invalidité (part patronale)",
    "320": "[FP] Surcotisation (part salariale)",
    "321": "[FP] Rachat des années d'études (part salariale)",
    "322": "[FP] Exonération de cotisation pour heures d’aide à domicile (part patronale)",
    "323": "[FP] Cotisation RAEP (part patronale)",
    "324": "[FP] Cotisation RAEP (part salariale)",
    "325": "[FP] Validation de services (part patronale)",
    "326": "[FP] Régularisation de service (part salariale)",
    "327": "[FP] Régularisation de service (part patronale)",
    "330": "Régime de base forfaitaire CNBF",
    "331": "Régime de base proportionnelle CNBF",
    "332": "Régime complémentaire CNBF",
    "333": "Cotisation contrat d’emploi pénitentiaire 1",
    "334": "Cotisation contrat d’emploi pénitentiaire 2",
    "901": "Cotisation épargne retraite",
    "902": "Contribution à la formation professionnelle des Artisans assimilés salariés",
    "903": "Cotisation AFNCA",
    "904": "Cotisation ANEFA",
    "905": "Cotisation ASCPA",
    "906": "Cotisation PROVEA",
    "907": "Complément de cotisation Assurance Maladie",
    "908": "Taxe forfaitaire CDDU Assurance Chômage",
    "909": "Cotisation au titre du financement des régimes de retraites supplémentaires à prestation définies",
    "910": "Exonération de cotisations patronales pour les entreprises affectées par la crise sanitaire",
    "911": "Réduction de cotisations patronales pour les entreprises du secteur de la vigne affectées par la crise sanitaire",
    "912": "Exonération du forfait social à 10%",
    "913": "Indemnité inflation",
    "914": "Réduction sapeurs-pompiers volontaires sur les contributions recouvrées par la MSA, l’Urssaf ou France Travail",
    "915": "Réduction sapeurs-pompiers volontaires sur les cotisations et contributions recouvrées par l’Agirc-Arrco",
    "916": "Exonération de cotisations applicable en Zones France Ruralités Revitalisation (ZFRR)",
    "917": "Potentielle nouvelle cotisation D",
    "918": "Versement mobilité régional et rural",
    "919": "Exonération de contribution patronale sur les indemnités de mise à la retraite d’un salarié en contrat de valorisation de l’expérience (CVE)",
    "920": "Potentielle nouvelle cotisation B",
}


def libelle_cotisation(code: Optional[str]) -> str:
    """Libellé officiel d'un code de cotisation, vide si le code est inconnu."""
    if not code:
        return ""
    return CODE_COTISATION_LIBELLE.get(str(code).zfill(3), "")
