# Schemas for schedules — ré-exports pour préparation migration.
from .ai import (
    AiCalendarProposalResponse,
    AiDayEntry,
    AiEmployeeProposal,
    ParseInstructionRequest,
    RosterEmployee,
    TimesheetExtractJobResponse,
    TimesheetExtractProgress,
    TimesheetExtractStartResponse,
)
from .requests import (
    ActualHoursEntry,
    ActualHoursRequest,
    ApplyModelRequest,
    ApplyPresetRequest,
    DayConfigModel,
    GenerateCalendarRequest,
    ImportBadgeuseBulkRequest,
    ImportBadgeuseEmployeeRequest,
    PlannedCalendarEntry,
    PlannedCalendarRequest,
    SchedulePlanUpsert,
    WeekConfigModel,
)
from .responses import (
    CalendarData,
    CalendarResponse,
    CumulsPeriode,
    CumulsResponse,
    CumulsValues,
)

__all__ = [
    "ActualHoursEntry",
    "ActualHoursRequest",
    "AiCalendarProposalResponse",
    "AiDayEntry",
    "AiEmployeeProposal",
    "ApplyModelRequest",
    "ApplyPresetRequest",
    "GenerateCalendarRequest",
    "SchedulePlanUpsert",
    "CalendarData",
    "CalendarResponse",
    "CumulsPeriode",
    "CumulsResponse",
    "CumulsValues",
    "DayConfigModel",
    "ImportBadgeuseBulkRequest",
    "ImportBadgeuseEmployeeRequest",
    "ParseInstructionRequest",
    "PlannedCalendarEntry",
    "PlannedCalendarRequest",
    "RosterEmployee",
    "TimesheetExtractJobResponse",
    "TimesheetExtractProgress",
    "TimesheetExtractStartResponse",
    "WeekConfigModel",
]
